version: '3'
services:
  percona:
    image: percona
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - percona_data:/var/lib/mysql
      - ./percona-init:/docker-entrypoint-initdb.d

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./mysql-init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  percona_data:
  postgres_data:
